cv_binary:
	./knn-cv.py -f ../data/knn_binary_data.csv -i 10 -o knn-cv-binary.png -q

cv_three:
	./knn-cv.py -f ../data/knn_three_class_data.csv -i 10 -o knn-cv-three.png -q

binary:
	./knn.py -f ../data/knn_binary_data.csv -o . -q

three:
	./knn.py -f ../data/knn_three_class_data.csv -o . -q
