laplace: l1 l2 l3

l1:
	./plot_laplace_approx.py -a 5 -b 5 -n 20 -y 10 -o laplace1.png

l2:
	./plot_laplace_approx.py -a 3 -b 15 -n 10 -y 3 -o laplace2.png

l3:
	./plot_laplace_approx.py -a 1 -b 30 -n 10 -y 3 -o laplace3.png
